@url = http://localhost:3000/generos

GET {{url}}

### buscar um gênero
GET {{url}}/1

### Criar um novo gênero
POST {{url}}
Content-Type: application/json

{
    "nome": "Policial"
}

### Atualizar um gênero
PUT {{url}}/2
Content-Type: application/json

{
    "nome": "Ficção Científica"
}

### Excluir um gênero
DELETE {{url}}/3